In [1]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np

In [3]:
# $VEHICLE:SIMRUN;NO;VEHTYPE;PTLINE;PTSTOP;SIMSEC
table_def = {'$VEHICLE:SIMRUN': np.int16, 'NO': np.int64, 'VEHTYPE': np.int16, 'PTLINE': np.int16, 'PTSTOP': np.int16, 'SIMSEC': np.float16}

In [16]:
df = pd.read_table(r'D:\Projects\2016\Python\Run_001.fzp',sep=';',skiprows=16)
df.head()

$VEHICLE:SIMRUN    NO  VEHTYPE  PTLINE  PTSTOP  SIMSEC
0                1     3     1301      14     NaN  1800.2
1                1     4     1301      15     120  1800.2
2                1  2199     1301      14     NaN  1800.2
3                1  2200     1301      15     NaN  1800.2
4                1  4411     1301      14     NaN  1800.2

In [17]:
df.dtypes

$VEHICLE:SIMRUN      int64
NO                   int64
VEHTYPE              int64
PTLINE               int64
PTSTOP             float64
SIMSEC             float64
dtype: object

In [11]:
# Drop all PTSTOP with NaN
df2 = df.dropna(axis=0)
df2.head()

$VEHICLE:SIMRUN     NO  VEHTYPE  PTLINE  PTSTOP  SIMSEC
1                 1      4     1301      15     120  1800.2
17                1  15399     1301      15     101  1800.2
19                1  15758     1301      17     116  1800.2
25                1      4     1301      15     120  1801.2
41                1  15399     1301      15     101  1801.2

In [21]:
# Group-by select the min simsec and max simsec
df2_group = df2.groupby(['NO','PTLINE', 'PTSTOP'])


In [22]:
df2_head = df2_group.head(1)

In [23]:
df2_tail = df2_group.tail(1)

In [26]:
# merge using ['NO','PTLINE', 'PTSTOP']
merged = pd.merge(df2_head, df2_tail, left_on = ['NO','PTLINE', 'PTSTOP'], right_on=['NO','PTLINE', 'PTSTOP'], suffixes=['_min','_max'])

In [88]:
merged_sort = merged.sort_values(by=['NO','PTLINE', 'SIMSEC_min'])
merged_sort[merged_sort['NO']==4]

$VEHICLE:SIMRUN_min  NO  VEHTYPE_min  PTLINE  PTSTOP  SIMSEC_min  \
0                     1   4         1301      15     120      1800.2   
42                    1   4         1301      15     126      2265.2   
89                    1   4         1301      15     122      2684.2   

    $VEHICLE:SIMRUN_max  VEHTYPE_max  SIMSEC_max  
0                     1         1301      1811.2  
42                    1         1301      2393.2  
89                    1         1301      2697.2

In [89]:
merged_sort.head(50)

$VEHICLE:SIMRUN_min     NO  VEHTYPE_min  PTLINE  PTSTOP  SIMSEC_min  \
40                     1      3         1301      14     102      2235.2   
0                      1      4         1301      15     120      1800.2   
42                     1      4         1301      15     126      2265.2   
89                     1      4         1301      15     122      2684.2   
9                      1   2199         1301      14     109      1904.2   
17                     1   2199         1301      14     108      1992.2   
22                     1   2199         1301      14     106      2054.2   
55                     1   2199         1301      14     102      2385.2   
5                      1   2200         1301      15     116      1853.2   
12                     1   2200         1301      15     118      1933.2   
24                     1   2200         1301      15     120      2057.2   
59                     1   2200         1301      15     126      2421.2   
94                     1   2200         1301      15     122      2715.2   
19                     1   4411         1301      14     109      2018.2   
31                     1   4411         1301      14     108      2107.2   
35                     1   4411         1301      14     106      2196.2   
69                     1   4411         1301      14     102      2545.2   
29                     1   4412         1301      15     114      2103.2   
37                     1   4412         1301      15     116      2202.2   
47                     1   4412         1301      15     118      2285.2   
52                     1   4412         1301      15     120      2356.2   
108                    1   4412         1301      15     126      2885.2   
143                    1   4412         1301      15     122      3218.2   
11                     1   6635         1301      14     112      1921.2   
34                     1   6635         1301      14     109      2184.2   
44                     1   6635         1301      14     108      2279.2   
51                     1   6635         1301      14     106      2347.2   
87                     1   6635         1301      14     102      2676.2   
30                     1   6636         1301      15     114      2105.2   
53                     1   6636         1301      15     120      2357.2   
109                    1   6636         1301      15     126      2889.2   
18                     1   8832         1301      14     113      1993.2   
38                     1   8832         1301      14     112      2220.2   
80                     1   8832         1301      14     109      2609.2   
92                     1   8832         1301      14     108      2699.2   
101                    1   8832         1301      14     106      2778.2   
134                    1   8832         1301      14     102      3147.2   
16                     1   8833         1301      15     124      1988.2   
25                     1   8833         1301      15     111      2071.2   
50                     1   8833         1301      15     114      2333.2   
62                     1   8833         1301      15     116      2468.2   
71                     1   8833         1301      15     118      2549.2   
83                     1   8833         1301      15     120      2653.2   
122                    1   8833         1301      15     126      3015.2   
162                    1   8833         1301      15     122      3388.2   
14                     1  11036         1301      14     119      1951.2   
23                     1  11036         1301      14     117      2056.2   
33                     1  11036         1301      14     115      2126.2   
45                     1  11036         1301      14     113      2280.2   
66                     1  11036         1301      14     112      2522.2   

     $VEHICLE:SIMRUN_max  VEHTYPE_max  SIMSEC_max  
40                     1         1301      2243.2  
0                      1

In [92]:
# compute the travel time = Next Arrival Time - Prev. Departure Time
depart = (merged_sort['SIMSEC_max'][0:len(merged_sort)-1]).values
arrival = (merged_sort['SIMSEC_min'][1:]).values

In [93]:
depart

array([ 2243.2,  1811.2,  2393.2,  2697.2,  1909.2,  1997.2,  2058.2,
        2391.2,  1876.2,  1936.2,  2092.2,  2519.2,  2718.2,  2023.2,
        2112.2,  2200.2,  2551.2,  2114.2,  2229.2,  2288.2,  2389.2,
        2997.2,  3223.2,  1941.2,  2190.2,  2286.2,  2353.2,  2682.2,
        2109.2,  2372.2,  2922.2,  2002.2,  2239.2,  2615.2,  2701.2,
        2782.2,  3153.2,  1991.2,  2106.2,  2345.2,  2488.2,  2553.2,
        2662.2,  3114.2,  3391.2,  1975.2,  2059.2,  2139.2,  2294.2,
        2550.2,  2926.2,  3019.2,  3104.2,  3443.2,  1860.2,  2096.2,
        2414.2,  2510.2,  2573.2,  2674.2,  3099.2,  3394.2,  2110.2,
        2300.2,  2459.2,  2684.2,  2925.2,  3019.2,  3104.2,  3440.2,
        1851.2,  2074.2,  2409.2,  2617.2,  2796.2,  2860.2,  2989.2,
        3589.2,  3952.2,  1865.2,  2571.2,  2653.2,  2723.2,  2881.2,
        3146.2,  3535.2,  3625.2,  3709.2,  3975.2,  1838.2,  1972.2,
        2225.2,  2299.2,  2526.2,  2739.2,  2850.2,  3236.2,  3374.2,
        3436.2,  356

In [94]:
arrival

array([ 1800.2,  2265.2,  2684.2,  1904.2,  1992.2,  2054.2,  2385.2,
        1853.2,  1933.2,  2057.2,  2421.2,  2715.2,  2018.2,  2107.2,
        2196.2,  2545.2,  2103.2,  2202.2,  2285.2,  2356.2,  2885.2,
        3218.2,  1921.2,  2184.2,  2279.2,  2347.2,  2676.2,  2105.2,
        2357.2,  2889.2,  1993.2,  2220.2,  2609.2,  2699.2,  2778.2,
        3147.2,  1988.2,  2071.2,  2333.2,  2468.2,  2549.2,  2653.2,
        3015.2,  3388.2,  1951.2,  2056.2,  2126.2,  2280.2,  2522.2,
        2918.2,  3015.2,  3098.2,  3435.2,  1844.2,  2072.2,  2408.2,
        2500.2,  2570.2,  2656.2,  3033.2,  3391.2,  2100.2,  2295.2,
        2457.2,  2670.2,  2922.2,  3017.2,  3100.2,  3436.2,  1837.2,
        2031.2,  2371.2,  2605.2,  2772.2,  2857.2,  2958.2,  3482.2,
        3942.2,  1854.2,  2551.2,  2649.2,  2718.2,  2875.2,  3121.2,
        3518.2,  3620.2,  3698.2,  3965.2,  1800.2,  1969.2,  2200.2,
        2283.2,  2468.2,  2736.2,  2822.2,  3222.2,  3356.2,  3431.2,
        3554.2,  391

In [95]:
tt = arrival - depart

In [86]:
tt[0]

453.99999999999977

In [96]:
tt2 = np.zeros(len(tt)+1)
tt2[1:] = tt
tt2

array([    0.,  -443.,   454.,   291.,  -793.,    83.,    57.,   327.,
        -538.,    57.,   121.,   329.,   196.,  -700.,    84.,    84.,
         345.,  -448.,    88.,    56.,    68.,   496.,   221., -1302.,
         243.,    89.,    61.,   323.,  -577.,   248.,   517.,  -929.,
         218.,   370.,    84.,    77.,   365., -1165.,    80.,   227.,
         123.,    61.,   100.,   353.,   274., -1440.,    81.,    67.,
         141.,   228.,   368.,    89.,    79.,   331., -1599.,   212.,
         312.,    86.,    60.,    83.,   359.,   292., -1294.,   185.,
         157.,   211.,   238.,    92.,    81.,   332., -1603.,   180.,
         297.,   196.,   155.,    61.,    98.,   493.,   353., -2098.,
         686.,    78.,    65.,   152.,   240.,   372.,    85.,    73.,
         256., -2175.,   131.,   228.,    58.,   169.,   210.,    83.,
         372.,   120.,    57.,   118.,   350.,   264., -2444.,   671.,
         156.,  -928.,    60.,    61.,   469.,   237.,  -655.,   868.,
      

In [97]:
merged_sort.drop('tt',axis=1, inplace=True)

ValueError: labels ['tt'] not contained in axis

In [101]:
merged_sort['tt'] = tt2

In [102]:
merged_sort[merged_sort['NO']==4]

$VEHICLE:SIMRUN_min  NO  VEHTYPE_min  PTLINE  PTSTOP  SIMSEC_min  \
0                     1   4         1301      15     120      1800.2   
42                    1   4         1301      15     126      2265.2   
89                    1   4         1301      15     122      2684.2   

    $VEHICLE:SIMRUN_max  VEHTYPE_max  SIMSEC_max   tt  
0                     1         1301      1811.2 -443  
42                    1         1301      2393.2  454  
89                    1         1301      2697.2  291

In [103]:
tt_out = merged_sort[merged_sort['tt']>0]
tt_out['tt'].describe()

count    322.000000
mean     217.322981
std      154.673029
min       56.000000
25%       91.250000
50%      174.000000
75%      306.750000
max      891.000000
Name: tt, dtype: float64